name: Main Branch CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        pytest tests/ -v --tb=short
    
    - name: Test training pipeline
      run: |
        python train.py
    
    - name: Test inference
      run: |
        python inference.py
    
    - name: Comment test results
      if: always()
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const message = `## 🎯 Main Branch Test Results
          
          ✅ Production tests completed!
          
          - Unit tests: PASSED
          - Training pipeline: PASSED
          - Inference: PASSED
          
          Branch: main
          Commit: ${{ github.sha }}
          Ready for deployment! 🚀
          `;
          
          if (context.eventName === 'pull_request') {
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });
          }
